{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject['project'] %}

{% set name = project['name'] %}
{% set version = VERSION %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  script:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}} {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - anaconda = anaconda_cli_base.cli:app

requirements:
  host:
    - python {{ project['requires-python'] }}
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python {{ project['requires-python'] }}
    {% for dep in project['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run_constrained:
    # Ensure that a version of anaconda-cli-base cannot be installed if an incompatible
    # older version of anaconda-client is installed.
    - anaconda-client>=1.13.0
    - anaconda-cloud-cli>=0.3.0

test:
  imports:
    - anaconda_cli_base
  commands:
    - anaconda --version
    - python -c "from anaconda_cli_base import __version__; assert __version__ == \"{{ version }}\""
about:
  summary: {{ project['description'] }}
  license: {{ project['license']['text'] }}
  license_file: LICENSE
